from typing import Any
import app.ui.widgets.actions.control_actions as control_actions

COMMON_LAYOUT_DATA: Any = {  # noqa: F811
    "Face Restorer": {
        "FaceRestorerEnableToggle": {
            "level": 1,
            "label": "Enable Face Restorer",
            "default": False,
            "help": "Enable the use of a face restoration model to improve the quality of the face after swapping.",
            "exec_function": control_actions.handle_restorer_state_change,
            "exec_function_args": ["FaceRestorerEnableToggle"],
        },
        "FaceRestorerTypeSelection": {
            "level": 2,
            "label": "Restorer Type",
            "options": [
                "GFPGAN-v1.4",
                "GFPGAN-1024",
                "CodeFormer",
                "GPEN-256",
                "GPEN-512",
                "GPEN-1024",
                "GPEN-2048",
                "RestoreFormer++",
                "VQFR-v2",
            ],
            "default": "GFPGAN-v1.4",
            "parentToggle": "FaceRestorerEnableToggle",
            "requiredToggleValue": True,
            "help": "Select the model type for face restoration.",
            "exec_function": control_actions.handle_model_selection_change,
            "exec_function_args": ["FaceRestorerTypeSelection"],
        },
        "FaceRestorerDetTypeSelection": {
            "level": 2,
            "label": "Alignment",
            "options": ["Original", "Blend", "Reference"],
            "default": "Original",
            "parentToggle": "FaceRestorerEnableToggle",
            "requiredToggleValue": True,
            "help": "Select the alignment method for restoring the face to its original or blended position.",
            "exec_function": control_actions.handle_restorer_state_change,
            "exec_function_args": ["FaceRestorerEnable2Toggle"],
        },
        "FaceFidelityWeightDecimalSlider": {
            "level": 2,
            "label": "Fidelity Weight",
            "min_value": "0.0",
            "max_value": "1.0",
            "default": "0.9",
            "decimals": 1,
            "step": 0.1,
            "parentToggle": "FaceRestorerEnableToggle",
            "requiredToggleValue": True,
            "help": "Adjust the fidelity weight to control how closely the restoration preserves the original face details (For CodeFormer and VQFR-v2 only).",
        },
        "FaceRestorerBlendSlider": {
            "level": 2,
            "label": "Blend",
            "min_value": "0",
            "max_value": "100",
            "default": "100",
            "step": 1,
            "parentToggle": "FaceRestorerEnableToggle",
            "requiredToggleValue": True,
            "help": "Control the blend ratio between the restored face and the swapped face.",
        },
        "FaceRestorerAutoEnableToggle": {
            "level": 2,
            "label": "Auto Restore",
            "default": False,
            "parentToggle": "FaceRestorerEnableToggle",
            "requiredToggleValue": True,
            "help": "Auto Adjust Restorer Blend Amount",
        },
        "FaceRestorerAutoSharpAdjustSlider": {
            "level": 3,
            "label": "Adjust Sharpness",
            "min_value": "-60",
            "max_value": "60",
            "default": "0",
            "step": 1,
            "parentToggle": "FaceRestorerEnableToggle & FaceRestorerAutoEnableToggle",
            "requiredToggleValue": True,
            "help": "Adjust sharp calc. mostly needed for over 0, which makes the swap sharper. depends on swap model, restorer model, resolution, face size,...",
        },
        "FaceRestorerAutoMaskEnableToggle": {
            "level": 3,
            "label": "Sharpness Mask",
            "default": False,
            "parentToggle": "FaceRestorerEnableToggle & FaceRestorerAutoEnableToggle",
            "requiredToggleValue": True,
            "help": "Auto Adjust Restorer Blend Amount with sharpness Map",
        },
        "FaceRestorerAutoSharpMaskAdjustDecimalSlider": {
            "level": 4,
            "label": "Mask Adjust",
            "min_value": "0.00",
            "max_value": "1.00",
            "default": "1.00",
            "decimals": 2,
            "step": 0.05,
            "parentToggle": "FaceRestorerEnableToggle & FaceRestorerAutoEnableToggle & FaceRestorerAutoMaskEnableToggle",
            "requiredToggleValue": True,
            "help": "Adjust Min/Max Blend value change from base auto Blend value",
        },
        "FaceRestorerEnable2Toggle": {
            "level": 1,
            "label": "Enable Face Restorer 2",
            "default": False,
            "help": "Enable the use of a face restoration model to improve the quality of the face after swapping.",
            "exec_function": control_actions.handle_restorer_state_change,
            "exec_function_args": ["FaceRestorerEnable2Toggle"],
        },
        "FaceRestorerEnable2EndToggle": {
            "level": 2,
            "label": "Apply at End",
            "default": False,
            "parentToggle": "FaceRestorerEnable2Toggle",
            "requiredToggleValue": True,
            "help": "Apply the second restorer at end of pipeline (after Face Editor to compensate the sharpness loss, befor final-blur and jpeg/mpeg-Compression. when disabled apply directly after first restorer like originaly.",
        },
        "FaceRestorerType2Selection": {
            "level": 2,
            "label": "Restorer Type",
            "options": [
                "GFPGAN-v1.4",
                "GFPGAN-1024",
                "CodeFormer",
                "GPEN-256",
                "GPEN-512",
                "GPEN-1024",
                "GPEN-2048",
                "RestoreFormer++",
                "VQFR-v2",
            ],
            "default": "GFPGAN-v1.4",
            "parentToggle": "FaceRestorerEnable2Toggle",
            "requiredToggleValue": True,
            "help": "Select the model type for face restoration.",
            "exec_function": control_actions.handle_model_selection_change,
            "exec_function_args": ["FaceRestorerType2Selection"],
        },
        "FaceRestorerDetType2Selection": {
            "level": 2,
            "label": "Alignment",
            "options": ["Original", "Blend", "Reference"],
            "default": "Original",
            "parentToggle": "FaceRestorerEnable2Toggle",
            "requiredToggleValue": True,
            "help": "Select the alignment method for restoring the face to its original or blended position.",
        },
        "FaceFidelityWeight2DecimalSlider": {
            "level": 2,
            "label": "Fidelity Weight",
            "min_value": "0.0",
            "max_value": "1.0",
            "default": "0.9",
            "decimals": 1,
            "step": 0.1,
            "parentToggle": "FaceRestorerEnable2Toggle",
            "requiredToggleValue": True,
            "help": "Adjust the fidelity weight to control how closely the restoration preserves the original face details.",
        },
        "FaceRestorerBlend2Slider": {
            "level": 2,
            "label": "Blend",
            "min_value": "0",
            "max_value": "100",
            "default": "100",
            "step": 1,
            "parentToggle": "FaceRestorerEnable2Toggle",
            "requiredToggleValue": True,
            "help": "Control the blend ratio between the restored face and the swapped face.",
        },
        "FaceRestorerAutoEnable2Toggle": {
            "level": 2,
            "label": "Auto Restore2",
            "default": False,
            "parentToggle": "FaceRestorerEnable2Toggle",
            "requiredToggleValue": True,
            "help": "Auto Adjust Restorer2 Blend Amount",
        },
        "FaceRestorerAutoSharpAdjust2Slider": {
            "level": 3,
            "label": "adjust sharpness",
            "min_value": "-60",
            "max_value": "60",
            "default": "0",
            "step": 1,
            "parentToggle": "FaceRestorerEnable2Toggle & FaceRestorerAutoEnable2Toggle",
            "requiredToggleValue": True,
            "help": "Adjust sharp calc. mostly needed for over 0, which makes the swap sharper. depends on swap model, restorer model, resolution, face size,...",
        },
        "FaceRestorerAutoMask2EnableToggle": {
            "level": 3,
            "label": "Sharpness Mask",
            "default": False,
            "parentToggle": "FaceRestorerEnable2Toggle & FaceRestorerAutoEnable2Toggle",
            "requiredToggleValue": True,
            "help": "Auto Adjust Restorer Blend Amount with sharpness Map",
        },
        "FaceRestorerAutoSharpMask2AdjustDecimalSlider": {
            "level": 4,
            "label": "Mask Adjust",
            "min_value": "0.00",
            "max_value": "1.00",
            "default": "1.00",
            "decimals": 2,
            "step": 0.05,
            "parentToggle": "FaceRestorerEnable2Toggle & FaceRestorerAutoEnable2Toggle & FaceRestorerAutoMask2EnableToggle",
            "requiredToggleValue": True,
            "help": "Adjust Min/Max Blend value change from base auto Blend value",
        },
    },
    "Face expressions": {
        "FaceExpressionBeforeTypeSelection": {
            "level": 1,
            "label": "Pipeline Position",
            "options": ["Beginning", "After First Restorer", "After Second Restorer"],
            "default": "Beginning",
            "help": "Select the Face Expression Restorer Editor position in the pipeline.",
        },
        "FaceExpressionEnableBothToggle": {
            "level": 1,
            "label": "Enable Face Expression Restorer",
            "default": False,
            "help": "Enabled the use of the LivePortrait face expression model to restore facial expressions after swapping.",
            "exec_function": control_actions.handle_face_expression_toggle_change,
            "exec_function_args": ["FaceExpressionEnableBothToggle"],
        },
        "FaceExpressionCropScaleBothDecimalSlider": {
            "level": 2,
            "label": "Crop Scale",
            "min_value": "2.0",
            "max_value": "3.0",
            "default": "2.3",
            "step": 0.1,
            "decimals": 1,
            "parentToggle": "FaceExpressionEnableBothToggle",
            "requiredToggleValue": True,
            "help": "Changes swap crop scale. Increase the value to capture the face more distantly.",
        },
        "FaceExpressionVYRatioBothDecimalSlider": {
            "level": 2,
            "label": "VY Ratio",
            "min_value": "-0.125",
            "max_value": "-0.100",
            "default": "-0.125",
            "step": 0.001,
            "decimals": 3,
            "parentToggle": "FaceExpressionEnableBothToggle",
            "requiredToggleValue": True,
            "help": "Changes the vy ratio for crop scale. Increase the value to capture the face more distantly.",
        },
        "FaceExpressionEyesToggle": {
            "level": 2,
            "label": "Restore The Eyes",
            "default": False,
            "parentToggle": "FaceExpressionEnableBothToggle",
            "requiredToggleValue": True,
            "help": "Activate the eyes face expression restorer",
        },
        "FaceExpressionRelativeEyesToggle": {
            "level": 3,
            "label": "Relative Position",
            "default": False,
            "parentToggle": "FaceExpressionEnableBothToggle & FaceExpressionEyesToggle",
            "requiredToggleValue": True,
            "help": "Makes the animation relative to the initial pose of the source image. Can be better for a more natural look.",
        },
        "FaceExpressionFriendlyFactorEyesDecimalSlider": {
            "level": 3,
            "label": "Eyes Expression Factor",
            "min_value": "0.0",
            "max_value": "2.0",
            "default": "1.0",
            "decimals": 1,
            "step": 0.1,
            "parentToggle": "FaceExpressionEnableBothToggle & FaceExpressionEyesToggle",
            "requiredToggleValue": True,
            "help": "Control the expression similarity between the driving face and the swapped face of the eyes.",
        },
        "FaceExpressionRetargetingEyesBothEnableToggle": {
            "level": 3,
            "label": "Retargeting Eyes",
            "default": False,
            "parentToggle": "FaceExpressionEnableBothToggle & FaceExpressionEyesToggle",
            "requiredToggleValue": True,
            "help": "Adjusting or redirecting the gaze or movement of the eyes during the facial restoration process.",
        },
        "FaceExpressionRetargetingEyesMultiplierBothDecimalSlider": {
            "level": 4,
            "label": "Eyes Multiplier",
            "min_value": "0.0",
            "max_value": "2.0",
            "default": "1.0",
            "decimals": 1,
            "step": 0.1,
            "parentToggle": "FaceExpressionRetargetingEyesBothEnableToggle & FaceExpressionEnableBothToggle & FaceExpressionEyesToggle",
            "requiredToggleValue": True,
            "help": "Multiplier value for Retargeting Eyes.",
        },
        "FaceExpressionNormalizeEyesBothEnableToggle": {
            "level": 4,
            "label": "Normalize Eyes",
            "default": True,
            "parentToggle": "FaceExpressionEnableBothToggle & FaceExpressionEyesToggle & FaceExpressionRetargetingEyesBothEnableToggle",
            "requiredToggleValue": True,
            "help": "Normalize the Eyes during the facial restoration process.",
        },
        "FaceExpressionNormalizeEyesThresholdBothDecimalSlider": {
            "level": 5,
            "label": "Eyes Threshold",
            "min_value": "0.10",
            "max_value": "1.00",
            "default": "0.40",
            "decimals": 2,
            "step": 0.01,
            "parentToggle": "FaceExpressionNormalizeEyesBothEnableToggle & FaceExpressionEnableBothToggle & FaceExpressionEyesToggle & FaceExpressionRetargetingEyesBothEnableToggle",
            "requiredToggleValue": True,
            "help": "Threshold for the eye open ratio, it will dictate at wich open/close ratio it uses the modified faceutil function.",
        },
        "FaceExpressionNormalizeEyesMaxBothDecimalSlider": {
            "level": 5,
            "label": "Max Open Ratio",
            "min_value": "0.00",
            "max_value": "1.00",
            "default": "0.50",
            "decimals": 2,
            "step": 0.01,
            "parentToggle": "FaceExpressionNormalizeEyesBothEnableToggle & FaceExpressionEnableBothToggle & FaceExpressionEyesToggle & FaceExpressionRetargetingEyesBothEnableToggle",
            "requiredToggleValue": True,
            "help": "Max eye open ratio that the target will have (<0.5 is best).",
        },
        "FaceExpressionLipsToggle": {
            "level": 2,
            "label": "Restore The Lips",
            "default": False,
            "parentToggle": "FaceExpressionEnableBothToggle",
            "requiredToggleValue": True,
            "help": "Activate the lips face expression restorer",
        },
        "FaceExpressionRelativeLipsToggle": {
            "level": 3,
            "label": "Relative Position",
            "default": False,
            "parentToggle": "FaceExpressionEnableBothToggle & FaceExpressionLipsToggle",
            "requiredToggleValue": True,
            "help": "Makes the animation relative to the initial pose of the source image. Can be better for a more natural look.",
        },
        "FaceExpressionFriendlyFactorLipsDecimalSlider": {
            "level": 3,
            "label": "Lips Expression Factor",
            "min_value": "0.0",
            "max_value": "2.0",
            "default": "1.0",
            "decimals": 1,
            "step": 0.1,
            "parentToggle": "FaceExpressionEnableBothToggle & FaceExpressionLipsToggle",
            "requiredToggleValue": True,
            "help": "Control the expression similarity between the driving face and the swapped face of the lips.",
        },
        "FaceExpressionRetargetingLipsBothEnableToggle": {
            "level": 3,
            "label": "Retargeting Lips",
            "default": False,
            "parentToggle": "FaceExpressionEnableBothToggle & FaceExpressionLipsToggle",
            "requiredToggleValue": True,
            "help": "Adjusting or modifying the position, shape, or movement of the lips during the facial restoration process.",
        },
        "FaceExpressionRetargetingLipsMultiplierBothDecimalSlider": {
            "level": 4,
            "label": "Lips Multiplier",
            "min_value": "0.0",
            "max_value": "2.0",
            "default": "1.0",
            "decimals": 1,
            "step": 0.1,
            "parentToggle": "FaceExpressionRetargetingLipsBothEnableToggle & FaceExpressionEnableBothToggle & FaceExpressionLipsToggle",
            "requiredToggleValue": True,
            "help": "Multiplier value for Retargeting Lips.",
        },
        "FaceExpressionNormalizeLipsBothEnableToggle": {
            "level": 3,
            "label": "Normalize Lips",
            "default": False,
            "parentToggle": "FaceExpressionEnableBothToggle & FaceExpressionLipsToggle",
            "requiredToggleValue": True,
            "help": "Normalize the lips during the facial restoration process.",
        },
        "FaceExpressionNormalizeLipsThresholdBothDecimalSlider": {
            "level": 4,
            "label": "Lips Threshold",
            "min_value": "0.00",
            "max_value": "0.20",
            "default": "0.03",
            "decimals": 2,
            "step": 0.01,
            "parentToggle": "FaceExpressionNormalizeLipsBothEnableToggle & FaceExpressionEnableBothToggle & FaceExpressionLipsToggle",
            "requiredToggleValue": True,
            "help": "Threshold value for Normalize Lips.",
        },
    },
}
